# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-25 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20181023_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=1, upload_to='teacher/%Y/%m', verbose_name='\u5934\u50cf'),
            preserve_default=False,
        ),
    ]
