# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-28 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20181028_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.TextField(default=1, max_length=500, verbose_name='\u8001\u5e08\u544a\u8bc9\u4f60'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='youneed_know',
            field=models.TextField(default=1, max_length=500, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
            preserve_default=False,
        ),
    ]
