# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-30 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181030_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
